### ISSUE TITLE
Support for GeoServer LayerGroups

### ISSUE THREAD

**Issue by natonic77** [kaktus40/Cesium-GeoserverTerrainProvider#12]
I have integrated GTP into a site I have built around Cesium and it is working great except when I try to load a geoserver layergroup that contains overlapping terrain layers (using geoserver dds plugin to pull in geotiffs that were build with goal_retile).  It appears almost as if the gray index from each layer is added to the others to provide a "composite" result (including adding -32768 from one sparse layer to valid elevations from a populated layer).  I was hoping to get the elevation from only the top layer (as designated by the layer order in geoserver) - and have missing data only passed through when none of the layers in the group have any data.  Is this supported?  If not, any suggestions for how to proceed?

**Comment by kaktus40** [comment]
Hello,
for me it seems more a problem (maybe not) for geoserver or the maintenair of bil/DDS plugin. As you said, the GeoserverTerrainProvider receive the sum of all layers in the group so it can't use only this sum and can't distinct each layer.
If the geoserver or bil/DDS team(s) can't respond to your request a workaround should be to work with GDAL (see gdal merge or gdal VRT) in order to merge the layers and so you will have one layer in geoserver.
