### ISSUE TITLE
only half of the world map is rendered

### ISSUE THREAD

**Issue by chaitanyajalluri** [kaktus40/Cesium-GeoserverTerrainProvider#36]
can u help where to modify/edit the method getTileDataAvailable exactly

**Comment by kaktus40** [comment]
you should modify [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/GeoserverTerrainProvider.js#L804), [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/GeoserverTerrainProvider.js#L373) and [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/GeoserverTerrainProvider.js#L576) in order to always return true

**Comment by chaitanyajalluri** [comment]
After doing the modifications specified above, I am able to get the full globe. But when I am loading the tile, black patches are appearing over the terrain. 
![Screenshot (3)](https://user-images.githubusercontent.com/41281254/63001544-7856ca80-be91-11e9-9ab2-9ee1e943fabb.png)

**Comment by ohadmanor** [comment]
I can offer you alternative way:
change the layer Lat/Lon Bounding Box to -180,-90,180,90 and it will work.

**Comment by chaitanyajalluri** [comment]
Thank you that issue is resolved
